on:
  pull_request:
  push:
    branches:
      - try/**
    tags-ignore:
      - v*.*.*
      - '[0-9]+.[0-9]+.[0-9]+'


name: Checks & Tests

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUST_LOG: trace

jobs:
  check-and-test:
    strategy:
      matrix:
        platform:
          - ubuntu
          - windows
          - macos
        toolchain:
          - stable
          - 1.76.0

    name: Test on ${{ matrix.platform }} with ${{ matrix.toolchain }}
    runs-on: "${{ matrix.platform }}-latest"

    steps:
      - uses: actions/checkout@v4
      #- uses: extractions/setup-just@v1
      - uses: mig4/setup-bats@v1
      - uses: taiki-e/install-action@v2
        with:
          tool: ripgrep
      - name: Configure toolchain
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --profile minimal --no-self-update -c clippy
          rustup default ${{ matrix.toolchain }}

      #- run: cargo check
      -  run: cargo install --debug --path .
      - run: cargo test -- --nocapture
      - run: bats test/*.bats

      - name: Clippy
        if: matrix.toolchain == 'stable'
        run: cargo clippy

  check-only:
    strategy:
      matrix:
        target:
          - x86_64-unknown-freebsd
          - x86_64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
          - aarch64-apple-darwin
          - aarch64-pc-windows-msvc
        include:
          - target: x86_64-unknown-freebsd
            platform: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            platform: ubuntu-latest
          - target: armv7-unknown-linux-gnueabihf
            platform: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            platform: ubuntu-latest
          - target: aarch64-apple-darwin
            platform: macos-latest
          - target: aarch64-pc-windows-msvc
            platform: windows-latest

    name: Check only for ${{ matrix.target }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: cargo check --target ${{ matrix.target }}
